
const fetchBooks = async () => {
    return [
        {
            id: 1,
            title: 'The Great Gatsby',
            author: 'F. Scott Fitzgerald',
            price: 15.99,
            description: 'A classic novel exploring themes of decadence, idealism, and the American Dream.',
            image: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f7/TheGreatGatsby_1925jacket.jpeg/220px-TheGreatGatsby_1925jacket.jpeg',
          },
          {
            id: 2,
            title: 'To Kill a Mockingbird',
            author: 'Harper Lee',
            price: 12.99,
            description: 'A powerful story of racial injustice and moral growth in the American South.',
            image: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/79/To_Kill_a_Mockingbird.jpg/220px-To_Kill_a_Mockingbird.jpg',
          },
          {
            id: 3,
            title: '1984',
            author: 'George Orwell',
            price: 14.99,
            description: 'A dystopian novel depicting a totalitarian society and the consequences of thought control.',
            image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/1984first.jpg/220px-1984first.jpg',
          },
          {
            id: 4,
            title: 'The Catcher in the Rye',
            author: 'J.D. Salinger',
            price: 11.99,
            description: 'A coming-of-age novel that explores themes of alienation and identity.',
            image: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/fc/The_Catcher_in_the_Rye_%28cover%29.jpg/220px-The_Catcher_in_the_Rye_%28cover%29.jpg',
          },
          {
            id: 5,
            title: 'Pride and Prejudice',
            author: 'Jane Austen',
            price: 13.99,
            description: 'A romantic novel that explores the social standing and expectations of women in the early 19th century.',
            image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/PrideandPrejudiceTitlePage.jpg/220px-PrideandPrejudiceTitlePage.jpg',
          },
          {
            id: 6,
            title: 'The Hobbit',
            author: 'J.R.R. Tolkien',
            price: 17.99,
            description: 'A fantasy novel that follows the journey of Bilbo Baggins as he embarks on an epic quest.',
            image: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8d/The_Hobbit_cover.jpg/220px-The_Hobbit_cover.jpg',
          },
          {
            id: 7,
            title: 'The Lord of the Rings',
            author: 'J.R.R. Tolkien',
            price: 24.99,
            description: 'A high fantasy novel that tells the story of the War of the Ring and the quest to destroy the One Ring.',
            image: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9d/The_Lord_of_the_Rings_%28black_cover%29.jpg/220px-The_Lord_of_the_Rings_%28black_cover%29.jpg',
          },
          {
            id: 8,
            title: 'Moby-Dick',
            author: 'Herman Melville',
            price: 18.99,
            description: 'A novel that follows the obsessive quest of Ahab, captain of the whaling ship Pequod, for revenge on a giant white sperm whale.',
            image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Moby-Dick_FE_title_page.jpg/220px-Moby-Dick_FE_title_page.jpg',
          },
          {
            id: 9,
            title: 'Frankenstein',
            author: 'Mary Shelley',
            price: 16.99,
            description: 'A Gothic novel exploring the consequences of scientific experimentation and the nature of humanity.',
            image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Frankenstein_1818_edition_title_page.jpg/220px-Frankenstein_1818_edition_title_page.jpg',
          },
          {
            id: 10,
            title: 'One Hundred Years of Solitude',
            author: 'Gabriel García Márquez',
            price: 20.99,
            description: 'A landmark novel in the magical realism genre, telling the multi-generational story of the Buendía family.',
            image: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/30/One_Hundred_Years_of_Solitude_%28book_cover%29.jpg/220px-One_Hundred_Years_of_Solitude_%28book_cover%29.jpg',
          },
          {
            id: 11,
            title: 'Brave New World',
            author: 'Aldous Huxley',
            price: 14.99,
            description: 'A dystopian novel that explores the dehumanizing effects of technological and social advancements.',
            image: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/62/BraveNewWorld_FirstEdition.jpg/220px-BraveNewWorld_FirstEdition.jpg',
          },
          {
            id: 12,
            title: 'The Odyssey',
            author: 'Homer',
            price: 16.99,
            description: 'An epic poem that follows the adventures of Odysseus as he tries to return home after the Trojan War.',
            image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Odyssey_father_picking_up_the_arms_of_his_son.jpg/220px-Odyssey_father_picking_up_the_arms_of_his_son.jpg',
          },
          {
            id: 13,
            title: 'The Picture of Dorian Gray',
            author: 'Oscar Wilde',
            price: 13.99,
            description: 'A philosophical novel that explores the consequences of indulgence and the pursuit of beauty.',
            image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Dorian_Gray_cover.jpg/220px-Dorian_Gray_cover.jpg',
          },
          {
            id: 14,
            title: 'The Brothers Karamazov',
            author: 'Fyodor Dostoevsky',
            price: 21.99,
            description: 'A novel that delves into the moral and spiritual struggles of the Karamazov family.',
            image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/The_Brothers_Karamazov_by_Fyodor_Dostoyevsky.jpg/220px-The_Brothers_Karamazov_by_Fyodor_Dostoyevsky.jpg',
          },
          {
            id: 15,
            title: 'Crime and Punishment',
            author: 'Fyodor Dostoevsky',
            price: 19.99,
            description: 'A psychological novel that explores the consequences of a young man decision to commit murder.',
            image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Raskolnikov_protz.jpg/220px-Raskolnikov_protz.jpg',
          },
          {
            id: 16,
            title: 'Wuthering Heights',
            author: 'Emily Brontë',
            price: 15.99,
            description: 'A Gothic novel that tells the tragic love story of Heathcliff and Catherine Earnshaw.',
            image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Wuthering_Heights_title_page.jpg/220px-Wuthering_Heights_title_page.jpg',
          },
          {
            id: 17,
            title: 'The Count of Monte Cristo',
            author: 'Alexandre Dumas',
            price: 18.99,
            description: 'An adventure novel that follows Edmond Dantès as he seeks revenge against those who wronged him.',
            image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/LeComteDeMonteCristo-frontispiece.jpg/220px-LeComteDeMonteCristo-frontispiece.jpg',
          },
          {
            id: 18,
            title: 'Anna Karenina',
            author: 'Leo Tolstoy',
            price: 20.99,
            description: 'A novel that explores the themes of love, infidelity, and societal expectations.',
            image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/%D0%9A%D0%BD%D0%B8%D0%B3%D0%B0_%D0%BE_%D0%BB%D1%8E%D0%B1%D0%B2%D0%B8.jpg/220px-%D0%9A%D0%BD%D0%B8%D0%B3%D0%B0_%D0%BE_%D0%BB%D1%8E%D0%B1%D0%B2%D0%B8.jpg',
          },
          {
            id: 19,
            title: 'The Iliad',
            author: 'Homer',
            price: 16.99,
            description: 'An epic poem that narrates the events of the Trojan War.',
            image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Iliad_%28Vatican%2C_Ms._Urb._gr._277%29%2C_folio_26_v.jpg/220px-Iliad_%28Vatican%2C_Ms._Urb._gr._277%29%2C_folio_26_v.jpg',
          },
          {
            id: 20,
            title: 'The War of the Worlds',
            author: 'H.G. Wells',
            price: 14.99,
            description: 'A science fiction novel depicting an alien invasion of Earth.',
            image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/The_War_of_the_Worlds_%281898%29_%28cropped%29.jpg/220px-The_War_of_the_Worlds_%281898%29_%28cropped%29.jpg',
          },
          {
            id: 21,
            title: 'Jane Eyre',
            author: 'Charlotte Brontë',
            price: 16.99,
            description: 'A Gothic novel that follows the life of Jane Eyre and her experiences as a governess.',
            image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Jane_Eyre_title_page.jpg/220px-Jane_Eyre_title_page.jpg',
          },
          {
            id: 22,
            title: 'The Grapes of Wrath',
            author: 'John Steinbeck',
            price: 17.99,
            description: 'A novel that explores the struggles of a family during the Great Depression.',
            image: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/09/Steinbeck_-_Grapes.jpg/220px-Steinbeck_-_Grapes.jpg',
          },
          {
            id: 23,
            title: 'The Scarlet Letter',
            author: 'Nathaniel Hawthorne',
            price: 15.99,
            description: 'A novel set in 17th-century Puritan Massachusetts, exploring the themes of sin and redemption.',
            image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/The_Scarlet_Letter_-_Nathaniel_Hawthorne.jpg/220px-The_Scarlet_Letter_-_Nathaniel_Hawthorne.jpg',
          },
          {
            id: 24,
            title: 'The Alchemist',
            author: 'Paulo Coelho',
            price: 14.99,
            description: 'A philosophical novel about Santiago journey to find his personal legend and achieve his dreams.',
            image: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/45/Alchemist_cover_new.jpg/220px-Alchemist_cover_new.jpg',
          },
          {
            id: 25,
            title: 'The Road',
            author: 'Cormac McCarthy',
            price: 19.99,
            description: 'A post-apocalyptic novel that follows a father and son journey through a desolate landscape.',
            image: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3c/The_Road_-_cover.jpg/220px-The_Road_-_cover.jpg',
          },
          {
            id: 26,
            title: 'The Shining',
            author: 'Stephen King',
            price: 18.99,
            description: 'A horror novel that tells the story of a family winter stay at an isolated and haunted hotel.',
            image: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Shiningnovel.jpg/220px-Shiningnovel.jpg',
          },
          {
            id: 27,
            title: 'Siddhartha',
            author: 'Hermann Hesse',
            price: 16.99,
            description: 'A philosophical novel that follows Siddhartha spiritual journey toward enlightenment.',
            image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Siddhartha.jpg/220px-Siddhartha.jpg',
          },
          {
            id: 28,
            title: 'The Martian',
            author: 'Andy Weir',
            price: 21.99,
            description: 'A science fiction novel about an astronaut struggle for survival on Mars.',
            image: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/The_Martian.jpg/220px-The_Martian.jpg',
          },
          {
            id: 29,
            title: 'The Girl with the Dragon Tattoo',
            author: 'Stieg Larsson',
            price: 17.99,
            description: 'A mystery thriller novel that follows investigative journalist Mikael Blomkvist and hacker Lisbeth Salander.',
            image: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/01/Thegirlwiththedragontattoo.jpg/220px-Thegirlwiththedragontattoo.jpg',
          },
          {
            id: 30,
            title: 'The Hitchhiker\'s Guide to the Galaxy',
            author: 'Douglas Adams',
            price: 14.99,
            description: 'A comedic science fiction series that follows the misadventures of Arthur Dent.',
            image: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/bd/H2G2_UK_front_cover.jpg/220px-H2G2_UK_front_cover.jpg',
          }
    
    ];
  };
  
  export { fetchBooks };
  